development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://zcgkvwhjynwxvg:kUA5t1V7JS9itBXaJCjfOahDnD@ec2-54-243-204-57.compute-1.amazonaws.com:5432/d6lgpot2pbiovr
